### ISSUE TITLE
Any chance for pre-built releases?

### ISSUE THREAD

**Issue by RobertGiesecke** [ArrowMaxGithub/Rust-vJoy-Manager#1]
Hi,

excited to see this project.
Been using joystick gremlin for years, but tbh python and the resulting variable latency has been the big downside of it (IMO).

I'm still fairly new to rust, and get a bunch of errors trying to build it.

I'll manage to build it in the long run, would really appreciate if there were a pre built binary tho :-)

cheers,
Robert

**Comment by ArrowMaxGithub** [comment]
I can certainly prepare some binaries, but the current state of the project really is alpha things are bound to break in future versions.
Ideally I would add more user-oriented features (easier rebind setup, 1-to-1 mappings, response curves, **documentation**) and lock down a version of the rebind-config-map to ensure backwards compatibility, first.

I'll add a binary for the current version, though.
Please understand that it's an undocumented alpha build.

Since you get build errors, can you share your OS and installed vJoy driver version and maybe a build log?

**Comment by RobertGiesecke** [comment]
thx for replying...
wrt build errors: I probably get all the errors a noob on Windows gets :D

I shouldn't have installed the vs build tools and rust using chocolatey before running the rust "installer".
It can't load libclang (the one from vs2022) and can't find  pkg-config

> Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)

It prob be easiest to just have it setup for windows cross compile in wsl2.

**Comment by RobertGiesecke** [comment]
I have it building... almost :D

![image](https://github.com/ArrowMaxGithub/Rust-vJoy-Manager/assets/782035/638d96c2-a5ac-4b32-9aa4-56642bb74795)

currently I'm using vjoy 2.1.9.1, but I also had 2.2.1-signed installed.
the newer one doesn't work with joystick gremlin.
which won't be a problem once I'm more fluent with rust.

here more details if you want them: 
- OS is Widnows 10
- I tried running it with stable/beta and nightly
- build log [build.log](https://github.com/ArrowMaxGithub/Rust-vJoy-Manager/files/12074173/build.log)

**Comment by ArrowMaxGithub** [comment]
Just pushed a release - feel free to let me know of any compatibility issues.

Wrt build logs: Either the GNU toolchain is misconfigured or there is an upstream issue with the SDL2 crate in combination with GNU, but I'm not entirely sure. I've only ever build the crate via msvc installed through rustup.

For the shortest quick-start ever, I've added a [basic usage guide](https://github.com/ArrowMaxGithub/Rust-vJoy-Manager/blob/0.1.0/BasicUsage.md).

In terms of future development: I'm currently preoccupied with other projects, but I will return here in due time and add more features. If you have any feedback, you can leave it here and I'll come back to it.
